### ISSUE TITLE
chatgpt-proxy-server提示：[SEVERE]: pthread_create: Operation not permitted (1)

### ISSUE THREAD

**Issue by gygy** [dqzboy/ChatGPT-Porxy#1]

**Comment by gittub996** [comment]
自建代理只能白嫖别人的吧？如果自己服务器能访问openai,直接使用API方式就好了吧

**Comment by dqzboy** [comment]
> 自建代理只能白嫖别人的吧？如果自己服务器能访问openai,直接使用API方式就好了吧

access_token 3.5gpt可以免费用，没有限制；API免费用户目前限流严重，后期需要掏钱，绑卡难度大于开plus。API的使用限制要比access_token低的多

**Comment by GNAYUOHZ** [comment]
Operation not permitted 
请问这个问题是什么原因

**Comment by gygy** [comment]
已经解决了

**Comment by zprelyx755** [comment]
> 已经解决了

可以请教一下是如何解决的吗
