### ISSUE TITLE
找不到 chatgpt-proxy-server  这个容器。

### ISSUE THREAD

**Issue by goyeee** [dqzboy/ChatGPT-Porxy#11]
```
4、检查是否正常
注意确保chatgpt-proxy-server运行正常
go-chatgpt-api需要初始化启动需要耐心等待
```

问题1：第4条要求检查server容器，我的yml文件如下，没有生成server容器。我想问下什么情况下才使用server容器呢？
我只启动了go-chatgpt-api 容器是不是也可以提供api的服务？

问题2：访问  我的公网IP:8080，目前返回{"errorMessage":"Missing accessToken."}，应该就代表go-chatgpt-api项目搭建好了吧？并且我的服务器已经通过 “如何让服务器科学上网”安装好了代理。wget google.com 是可以获取到回应的。但是我不知道我的代理IP是多少？ 装完之后得到了两个地址，分别是  我的公网IP:9999和 172.27.12.173:9999, 这个172.27.12.173:9999 会不会就是我的内网代理地址？需要填写到yml的 GO_CHATGPT_API_PROXY 上吗？

问题3：然后我使用第三方前端配置上accessToken后，go-chatgpt-api容器的日志如下，但是返回了404.

![image](https://user-images.githubusercontent.com/45221885/236637983-23c9b9d8-927a-403d-bf75-71c0228a8695.png)

不知道我的问题是不是有点小白，感谢回复。

**Comment by dqzboy** [comment]
问题1：chatgpt-proxy-server 目前已经不需要这个容器了 文档没有做更新 稍后我进行更新文档
问题2：返回{"errorMessage":"Missing accessToken."}说明接口通
代理的话，看你是如何部署的，宿主机部署的话自己你的服务器内网IP+代理端口
问题3：接口更新了  http://127.0.0.1:8080/chatgpt/conversation
