### ISSUE TITLE
🐞 反馈问题：

### ISSUE THREAD

**Issue by 2521245392** [dqzboy/ChatGPT-Porxy#21]
### 前置确认

- [X] 我确认我的网络可以访问openai，使用的是最新脚本，并且服务器规格 > 1C1G

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 复现步骤 🕹

按照教程正常安装，docker-compose.yml文件内容如下：
version: "3" 
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    network_mode: host   # 可选，将容器加入主机网络模式，即与主机共享网络命名空间；上面的端口映射将失效
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Shanghai
      - PROXY=http://127.0.0.1:7890   # GO_CHATGPT_API_PROXY=：可配置科学上网代理地址，例如：http://clash_vpsIP:7890；注释掉或者留空则不启用
      - ARKOSE_TOKEN_URL=
      - BX=
      - BX_URL=
      - OPENAI_EMAIL=
      - OPENAI_PASSWORD=
      - CONTINUE_SIGNAL=1  # CONTINUE_SIGNAL=1，开启/imitate接口自动继续会话功能，留空关闭，默认关闭
    restart: unless-stopped

### 问题描述 😯

反代搭建好了，也没有报错，但是在这些项目接入自建反代运行并没有效果

### 终端日志 📒

![E8BFCA48BFA91217F330B1A23CF793FB](https://github.com/dqzboy/ChatGPT-Proxy/assets/62867265/dee403c8-44a6-48fe-a837-919a156eefc1)
![0998E613A6A41CC835DFB48CCE27C128](https://github.com/dqzboy/ChatGPT-Proxy/assets/62867265/238b0c6b-a6f6-4a8c-9f7c-ebfbc897f29b)

**Comment by dqzboy** [comment]
看报错是没传入token或者api呀，你用的啥项目接入的？用的啥模型
