### ISSUE TITLE
ERRO[0030] Please make sure chatgpt proxy service is running

### ISSUE THREAD

**Issue by iBoundary** [dqzboy/ChatGPT-Porxy#3]
ERRO[0030] Please make sure chatgpt proxy service is running

**Comment by dqzboy** [comment]
docker ps检查容器是否运行

**Comment by iBoundary** [comment]
@dqzboy 
![image](https://user-images.githubusercontent.com/37945727/232767504-5863b245-bcae-488d-b58f-110c80dc85cb.png)

**Comment by iBoundary** [comment]
ERRO[0030] Please make sure chatgpt proxy service is running
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x7af96b]

goroutine 24 [running]:
github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh.func1()
        /app/webdriver/refresh.go:13 +0x2b
created by github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh
        /app/webdriver/refresh.go:12 +0x6a
ERRO[0030] Please make sure chatgpt proxy service is running
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x7af96b]

goroutine 20 [running]:
github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh.func1()
        /app/webdriver/refresh.go:13 +0x2b
created by github.com/linweiyuan/go-chatgpt-api/webdriver.Refresh
        /app/webdriver/refresh.go:12 +0x6a
ERRO[0030] Please make sure chatgpt proxy service is running

**Comment by dqzboy** [comment]
chatgpt-proxy-server看下这个容器日志报啥错误

**Comment by iBoundary** [comment]
没看到什么错误：
![image](https://user-images.githubusercontent.com/37945727/232769793-945c1dfd-c85d-4ee5-b928-ce2467081511.png)

**Comment by iBoundary** [comment]
Docker version 23.0.4, build f480fb1

**Comment by iBoundary** [comment]
ubuntu 22.10

**Comment by dqzboy** [comment]
多大的内存，报错是空指针

**Comment by iBoundary** [comment]
@dqzboy 
![image](https://user-images.githubusercontent.com/37945727/232772876-8497a823-6315-4f63-841e-babc76c47b23.png)

**Comment by dqzboy** [comment]
docker-compose.yml中CHATGPT_PROXY_SERVER地址没变吧。进入go-chatgpt-api容器里面。ping下这个地址 看看能不能通

**Comment by iBoundary** [comment]
我这个有错误吗：services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080  # 容器端口映射到宿主机8080端口；宿主机监听端口可按需改为其它端口
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
#      - NETWORK_PROXY_SERVER=http://localhost:7890     # NETWORK_PROXY_SERVER：科学上网地址
#      - NETWORK_PROXY_SERVER=socks5://localhost:7890
    depends_on:
      - chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

**Comment by dqzboy** [comment]
进入go-chatgpt-api容器里  看下chatgpt-proxy-server这个地址能不能ping通

**Comment by iBoundary** [comment]
@dqzboy 
![image](https://user-images.githubusercontent.com/37945727/232776427-befd7fae-3690-4927-a8d4-0aa79569ee1b.png)
