### ISSUE TITLE
按照方法走，但是还是出现 Access denied

### ISSUE THREAD

**Issue by whiteple** [dqzboy/ChatGPT-Porxy#4]
version: '3'
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080  # 容器端口映射到宿主机8080端口；宿主机监听端口可按需改为其它端口
    environment:
      - GIN_MODE=release
      - CHATGPT_PROXY_SERVER=http://chatgpt-proxy-server:9515
      - NETWORK_PROXY_SERVER=socks5://chatgpt-proxy-server-warp:65535
    depends_on:
      - chatgpt-proxy-server
      - chatgpt-proxy-server-warp
    restart: unless-stopped

  chatgpt-proxy-server:
    container_name: chatgpt-proxy-server
    image: linweiyuan/chatgpt-proxy-server
    restart: unless-stopped

  chatgpt-proxy-server-warp:
    container_name: chatgpt-proxy-server-warp
    image: linweiyuan/chatgpt-proxy-server-warp
    restart: unless-stopped

是不是哪里没有配置好？

**Comment by dqzboy** [comment]
服务器IP问题，应该被重点关注了

**Comment by 2018ybq** [comment]
ChatGPT error 523: 

<div id="cf-error-details" class="p-0">
    <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
        <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
          
          <span class="inline-block">Origin is unreachable</span>
          <span class="code-label">Error code 523</span>
        </h1>
        <div>
           Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_523&utm_campaign=bypass.churchless.tech" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
        </div>
        <div class="mt-3">2023-04-18 13:22:42 UTC</div>
    </header>
    
    <div class="my-8 bg-gradient-gray">
        <div class="w-240 lg:w-full mx-auto">
            <div class="clearfix md:px-8">
<span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
<span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
You
Browser
Working
Los Angeles
[Cloudflare](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_523&utm_campaign=bypass.churchless.tech)
Working
<span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
<span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
bypass.churchless.tech
我的出现这种情况是什么意思，昨天是报这个[OpenAI] 错误的网关 |  Bad Gateway
