### ISSUE TITLE
出现failed, reason: socket hang up

### ISSUE THREAD

**Issue by programday** [dqzboy/ChatGPT-Porxy#5]
配置好自建的代理，出现failed, reason: socket hang up，国内服务器，看的[国内服务器实现科学上网](https://www.dqzboy.com/13754.html)这篇文章配置，进入容器访问Google是可以请求的，

**Comment by dqzboy** [comment]
你代理有问题吧，能访问chat.openai.com吗？

**Comment by programday** [comment]
是可以访问的，容器内外都行curl https://chat.openai.com，不过还是出现了cf验证，docker logs -f go-chatgpt-api ，没有输出任何内容

**Comment by dqzboy** [comment]
```shell
docker exec chatgpt-proxy-server curl -x socks5://代理 ipinfo.io
```
看下你的IP，应该还是你的IP不干净导致的
