### ISSUE TITLE
请问这是什么问题？

### ISSUE THREAD

**Issue by ieiian** [dqzboy/ChatGPT-Porxy#8]
root@jiang:~/chatGPTproxy# sudo docker-compose up -d
Creating network "chatgptproxy_default" with the default driver
Creating chatgpt-proxy-server ... done
Creating go-chatgpt-api       ... done
root@jiang:~/chatGPTproxy# docker logs -f chatgpt-proxy-server 
Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1682060685.122][SEVERE]: pthread_create: Operation not permitted (1)
Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1682060686.564][SEVERE]: pthread_create: Operation not permitted (1)
Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1682060687.504][SEVERE]: pthread_create: Operation not permitted (1)
[1682060688.612][SEVERE]: pthread_create: Operation not permitted (1)
Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1682060690.159][SEVERE]: pthread_create: Operation not permitted (1)
Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1682060692.461][SEVERE]: pthread_create: Operation not permitted (1)
Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 9515
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1682060696.482][SEVERE]: pthread_create: Operation not permitted (1)
root@jiang:~/chatGPTproxy# nano docker-compose.yml 

这个请帮忙看一下是什么问题？似乎是权限的问题？

**Comment by dqzboy** [comment]
是docker安全机制限制；啥系统？乌班图？看下是不是你本地安全模块没关闭

**Comment by dqzboy** [comment]
不关闭安全模块，那就在docker-compose.yml 添加参数 privileged: true 试试

**Comment by ieiian** [comment]
> 不关闭安全模块，那就在docker-compose.yml 添加参数 privileged: true 试试

确实是，= =，谢谢。
