### ISSUE TITLE
自建代理老是被别人扫咋解决

### ISSUE THREAD

**Issue by 1205129045x** [dqzboy/ChatGPT-Porxy#9]
我是直接部署在外国服务器上的，是直接连接，就是`vpsip`加代理端口。
后台一看，经常有别人的IP访问，显示`missing acess token`

**Comment by dqzboy** [comment]
代理端口你公布在公网的？

**Comment by dqzboy** [comment]
那就是暴露在公网的 那被扫描很正常呀，把8080端口改成其他或者8080端口不对外暴露
